### ISSUE TITLE
masked channels

### ISSUE THREAD

**Issue by Sekunde** [3ammor/Video-Pixel-Networks#1]
if mask_type == 'A':
                mask[center_h, center_w, :channels_masked, :] = 0.

why you masked the in_channels from 0 to channels_masked? shouldn't it be 
mask[center_h, center_w, **channels_masked:**, :] = 0.

And there is only 'A' type mask in your code, where is 'B' type masks?

**Comment by o-tawab** [comment]
Masked constitutional layers are used to mask the ground truth, so each pixel only looks at the ground truth of the pixels before it. I concatenated the ground truth to the feature map, resulting the ground truth being in the first few channels. Therefor we mask the first (channels_masked) channels. by zeroing them in the weights. ```mask[center_h, center_w, :channels_masked, :] = 0 ``` 

About using masks type B, we can't use them because of the residual connections. If you think about it for a moment you will find that using mask A is essential in the first layer. And so in the rest of them because we added the input to the output of the first block (by the residual connection), that input containes the ground truth. So it's like we are allowing the next layer to see the ground truth.
I tried it BTW, it resulted converging faster at training time, but at test time it always predict black image because it can't see the ground truth that it used to see.
